### ISSUE TITLE
BUG: Anzahl der Mitarbeiter wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by Lennnard** [gripss-x/GRIPSS-X#10]
In der Allgemein-Seite des Unternehmens wird in der Übersicht angezeigt, dass das Unternehmen 2 Mitarbeiter hätte, obwohl ich der einzige Mitarbeiter bin.

![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152264718/b9cf36eb-fa0b-413c-9af9-e763e5763c06)

**Comment by Tech92Nick** [comment]
Same here.

**Comment by Graefenstein** [comment]
dito

**Comment by Marcel-Hahn** [comment]
#21
