### ISSUE TITLE
Bug: Unternehmensmatching

### ISSUE THREAD

**Issue by David-Kikl** [gripss-x/GRIPSS-X#100]
Ausschreibungen können über Freitextsuche nicht gefunden werden

**Comment by David-Kikl** [comment]
![image](https://github.com/gripss-x/GRIPSS-X/assets/152616581/d7fe3a67-0577-4fc8-87d9-9c061763953f)

**Comment by Marcel-Hahn** [comment]
kann ich nicht reproduzieren, könnte aber auch inzwischen bereits gelöst sein
