### ISSUE TITLE
Bug: Secret

### ISSUE THREAD

**Issue by David-Kikl** [gripss-x/GRIPSS-X#102]
Beim Hinzufügen eines Secrets ist jeder User einsehbar, der auf der Plattform angemeldet ist und auswählbar. 
![secret](https://github.com/gripss-x/GRIPSS-X/assets/152616581/08455fac-a430-4b4a-b1ca-b8f916b58f05)

**Comment by Marcel-Hahn** [comment]
Da werden alle Rollen angezeigt, die du hast. Du bist noch in der Superuser Gruppe und hast damit alle Rollen.
Ich nimm dich mal in der Gruppe raus, dann solltest du es nicht mehr sehen.
