### ISSUE TITLE
Bug: Projekte speichern

### ISSUE THREAD

**Issue by acwa3055** [gripss-x/GRIPSS-X#103]
Obwohl eine Leistung hinzugefügt ist, bekommt man eine Fehlermeldung wenn man das Projekt speichern möchtet
![Uploading Projekt speichern.png…]()
![Leistung](https://github.com/gripss-x/GRIPSS-X/assets/151533624/e2737301-7706-4e78-96ed-5c8b73921f4a)

**Comment by Marcel-Hahn** [comment]
kann ich nicht reproduzieren, könnte aber auch inzwischen bereits gelöst sein
