### ISSUE TITLE
Bug: Beschreibungsfeld zu klein

### ISSUE THREAD

**Issue by acwa3055** [gripss-x/GRIPSS-X#104]
Ich möchte ein neues Angebot erstellen, aber das Feld ,,Beschreibung" ist zu klein für mein Text (der nicht so riesig ist).

**Comment by Marcel-Hahn** [comment]
Du kannst je nach Browser das Feld eigenständig vergrößern oder sobald die KI Tools soweit sind, sollte das Feld ja automatisch ausgefüllt werden.

So geht das bei meinem Browser: https://github.com/gripss-x/GRIPSS-X/assets/866882/490a671c-4931-4658-91e9-f570a30544bc
