### ISSUE TITLE
BUG: Auswahl Ausschreibung beim Unternehmensmatching nicht möglich

### ISSUE THREAD

**Issue by Ralle311** [gripss-x/GRIPSS-X#14]
Wenn ich eine Ausschreibung erstellt habe ist es nicht Möglich diese auszuwählen wenn ich nach einem Dienstleister dafür suchen möchte.
![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152156790/fe246006-cb32-4e51-b08d-f79422748ee0)
![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152156790/b41d8777-b945-4d14-b7e8-cc643f2f6754)
![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152156790/9c1da548-2a45-4841-93bb-46b3cc5ee38f)

**Comment by Marcel-Hahn** [comment]
Behoben mit Version v2024.1.0-2611
