### ISSUE TITLE
Bug: Unternehmens-Matching -> Liste konnte nicht geladen werden

### ISSUE THREAD

**Issue by Tech92Nick** [gripss-x/GRIPSS-X#17]
Beim Öffnen des Reiters "Unternehmens-Matching" erscheint eine Fehlermeldung wie folgt.

![grafik](https://github.com/gripss-x/GRIPSS-X/assets/70604851/3812fcbc-589c-4afc-b9ad-dcacccad9840)

**Comment by Marcel-Hahn** [comment]
Behoben mit Version v2024.1.0-2611
