### ISSUE TITLE
BUG: Schrift zu dunkel (Dark Mode)

### ISSUE THREAD

**Issue by Graefenstein** [gripss-x/GRIPSS-X#18]
Die Schriftfarbe ist bei schwarzem Hintergund schlecht gewählt da kaum lesbar. 
![image](https://github.com/gripss-x/GRIPSS-X/assets/152511851/f007a884-95b9-4cb7-abd6-86ee5ba41251)
Siehe Screenshot

**Comment by Marcel-Hahn** [comment]
Ist ein bekannter Bug, der demnächst beseitigt sein sollte.

Zur internenn nach Verfolgung: https://github.com/hahnprojects/hpc/issues/259

**Comment by Marcel-Hahn** [comment]
behoben ab v2023.5.0-2564
