### ISSUE TITLE
BUG: keine Logindaten vorhanden

### ISSUE THREAD

**Issue by acwa3055** [gripss-x/GRIPSS-X#2]
Wie soll ich mich einloggen?

![image](https://github.com/gripss-x/GRIPSS-X/assets/151533624/7bb71874-826f-4a46-8b06-f76c2b1c6b8f)

**Comment by Marcel-Hahn** [comment]
Die Registrierung ist wieder aktiv:

![Registrierung](https://github.com/gripss-x/GRIPSS-X/assets/866882/55048b90-e950-4fd7-8c93-31e42923e7ae)
