### ISSUE TITLE
Bug: Mitarbeiter kann nicht angelegt werden

### ISSUE THREAD

**Issue by David-Kikl** [gripss-x/GRIPSS-X#23]
Wenn die Mailadresse von david.kiklhorn@iml.fraunhofer.de versucht wird einzuladen (oder andere Mailadressen) erscheint eine Fehlermeldung
![image](https://github.com/gripss-x/GRIPSS-X/assets/152616581/07f60e83-3290-44aa-a45b-2ee32a4086f3)

**Comment by Marcel-Hahn** [comment]
siehe #27
