### ISSUE TITLE
Rückfrage: Läuft jede Zertifizierung irgendwann ab?

### ISSUE THREAD

**Issue by dhefft** [gripss-x/GRIPSS-X#28]
Vielleicht wäre es auch schlau wenn die Zertifikate nochmal geprüft werden durch ein Clearinghouse (im Sinne von G-X) und angepasst werden könnten.

![grafik](https://github.com/gripss-x/GRIPSS-X/assets/148070856/20741484-56a2-4ef8-a700-13e7ebd4e4a1)

**Comment by Marcel-Hahn** [comment]
ja, wäre nice, ist aber glaube erst mal out-of-scope
