### ISSUE TITLE
UX: Auswahlliste Zertifikate

### ISSUE THREAD

**Issue by dhefft** [gripss-x/GRIPSS-X#29]
Doppelungen sollten nicht in der Liste auftauchen. Liste sortieren (alphabetisch). Dynamische Suche bei Buchstabeneingabe klasse!

![grafik](https://github.com/gripss-x/GRIPSS-X/assets/148070856/47d26516-6b14-4e8a-8546-349b7183fd3c)

**Comment by Marcel-Hahn** [comment]
doppelte Einträge sollten jetzt nicht mehr möglich sein
