### ISSUE TITLE
DE000000000 wird als gültige USt-IdNr Nummer akzeptiert.

### ISSUE THREAD

**Issue by EmilySophie9999** [gripss-x/GRIPSS-X#35]
Ist das eine gültige USt-IdNr Nummer?

**Comment by Marcel-Hahn** [comment]
Für die Testphase würden wir es jetzt erstmal so lassen, da sich damit leichter Dummy Unternehmen anlegen lassen. Später sollte sowas eh über den Beglaubigungsservice von GAIA-X gemacht werden. Daher würde ich das hier erstmal schließen
