### ISSUE TITLE
Unternehmens-LOGO wird nach dem Kreieren des Unternehmens nicht gespeichert

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#38]
*Beschreibe den Bug**
Unternehmens-LOGO wird nach dem Kreieren des Unternehmens nicht gespeichert

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
1. Neues Unternehmen hinzufügen
2. Daten ausfüllen
3. LOG-Auswählen
4. Speichern

**Erwartetes Verhalten**
Eine klare Beschreibung darüber, welche Funktion hier erwartet worden ist.

**Screenshots**
Wenn möglich, Screenshots ergänzen.

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by Marcel-Hahn** [comment]
Ich kann das nicht reproduzieren: [Screen Recorder Video](https://github.com/gripss-x/GRIPSS-X/assets/866882/183af4bf-5e9a-4926-9b40-f8f15e1d0d21)
@sadusmatthias Kannst du den Bug nochmal bitte genauer beschreiben?

**Comment by sadusmatthias** [comment]
ES hat heute bei mir einwandfrei funktioniert. Das Issue können wir schließen
