### ISSUE TITLE
Projektdaten können nicht gespeichert werden

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#39]
*Beschreibe den Bug**
Eine klare Beschreibung des auftretendes Bugs

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
1. Projektdaten aufrufen
2. LOGO hinzufügen
3. Klicken auf "Speichern"

**Erwartetes Verhalten**
Eine klare Beschreibung darüber, welche Funktion hier erwartet worden ist.

**Screenshots**
Siehe Screeshot

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

![Image](https://github.com/gripss-x/GRIPSS-X/assets/152488634/32616faa-3bfb-4045-88c1-4b24f72abfcf)

**Comment by sadusmatthias** [comment]
Nach dem entfernen des LOGO kann das Projekt trotzdem nicht gespeichert werden. Es folgt die gleiche Fehlermeldung.

**Comment by sadusmatthias** [comment]
Auch bi diesem Szenario erfolgt die gleiche Fehlermeldung:
Projektdaten aufrufen
Klicken auf "Speichern" (ohne etwas zu verändern)

**Comment by sadusmatthias** [comment]
Der Fehler erscheint nur bei diesem Unternehmen:

Weber Industrieller Rohrleitungsbau & Anlagenbau Merseburg GmbH & Co. KG

Auffällig ist, dass die PLZ bei diesem Unternehmen 4-stellig ist.

**Comment by Marcel-Hahn** [comment]
Das müssen wir uns mal genauer ansehen

**Comment by Marcel-Hahn** [comment]
Das wird jetzt besser dargestellt
![image](https://github.com/gripss-x/GRIPSS-X/assets/866882/0262a427-7138-4277-9f9b-ba8ee2a6475d)
