### ISSUE TITLE
Rolle als Unternehmens-übergreifende Funktion

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#40]
**Als ** [Beschreiben: Nutzer aus dem Unternehmen], **möchte ich** Y **sodass** Z.
Als Administrator der GRIPSS_X-Cloud möchte ich Rollen Unternehmens-Übergreifend definieren. Wenn ich z. B. eine Rolle "Vertriebsmitarbeiter" erstelle und konfiguriere, möchte ich, dass diese Rolle in allen von mir kreierten Unternehmen verfügbar ist und der hinzugefügten Mitarbeitern zugewiesen werden kann. 

### Beispiele
Es wird die Rolle "Vertriebsmitarbeiter" mit folgenden Rechten kreiert:

Lese-Zugriff auf alle Bereiche innerhalb des eigenen Unternehmens
Kein Zugriff auf Daten anderer Unternehmen
Schreibzugriff auf alle Anfragedaten
Schreibzugriff auf alle Angebotsdaten

Diese Rolle wird den Mitarbeitern Müller, Mayer, Schmidt im Unternehmen 1 zugewiesen
Diese Rolle wird den Mitarbeitern Schneider, Fischer   im Unternehmen 2 zugewiesen

### Akzeptanzkriterien
- [ ] Feld XY
- [ ] Farbe muss blau sein

### Ressourcen:
* weitere Informationen, Screenshots, Beispiele etc.

**Comment by Marcel-Hahn** [comment]
Das ist schwierig und nicht im Rahmen des Projektes umsetzbar. Ich übernehme das in unser Backlog und schließe ich das hier erstmal.
