### ISSUE TITLE
Ein Passwort wird angezeigt - Sicherheitsproblem

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#44]
*Beschreibe den Bug**
In der Vorschlagsliste des Eingabefeldes für den Namen eines neuen Mitarbeiters, wird ein Passwort aus eine völlig anderen Cloud-System angezeigt.

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
1. Neuen Mitarbeiter hinzufügen
2. In das Feld email klicken

**Erwartetes Verhalten**
Eine klare Beschreibung darüber, welche Funktion hier erwartet worden ist.

**Screenshots**
Siehe Screenshot

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by sadusmatthias** [comment]
Siehe Screenshot

![Image](https://github.com/gripss-x/GRIPSS-X/assets/152488634/5e3e697f-c910-4286-b30a-0c12a613e350)

**Comment by Marcel-Hahn** [comment]
Das ist kein von uns erstelltes Features. Scheinbar hast du das Passwort in deinem Browser als E-Mail Formular Eingabe gespeichert.
Ist in jedem Fall ein Sicherheitsproblem und du solltest zum einen die Formulardaten in deinem Browser löschen, sowie dieses Passwort, überall wo du es verwendet hast, ändern.
