### ISSUE TITLE
Fehlermeldung kryptisch

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#46]
*Beschreibe den Bug**
Falsche Einga

be im Feld - siehe Screenshot

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
1. Neuen Mitarbeiter einladen
2. Flasche E-Mail-Adresse eingeben 
3. Speichern

**Erwartetes Verhalten**
Eine klare Fehlermeldung: "Sie haben eine falsche E-Mail-Adresse" eingegeben

**Screenshots**
Siehe Screenshot.

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by sadusmatthias** [comment]
![Image](https://github.com/gripss-x/GRIPSS-X/assets/152488634/47c591de-e6a2-4745-9e02-f314e0da0ec6)

**Comment by Marcel-Hahn** [comment]
![image](https://github.com/gripss-x/GRIPSS-X/assets/866882/ea0654e6-1b15-4566-96a1-37022e0ad614)

Behoben mit Version v2024.1.0-2611
