### ISSUE TITLE
Zertifizierung/Qualifizierungsname erlaubt nur Werte aus einer Auswahlliste

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#48]
*Beschreibe den Bug**
Zertifizierung/Qualifizierungsname erlaubt nur Werte aus einer Auswahlliste

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
1. Zertifizierung/Qualifizierung hinzufügen
2.Eigene Zertifizierung eingeben

**Erwartetes Verhalten**
Die Eingaben sollen nicht auf die Werteliste beschränkt sein..

**Screenshots**
Siehe Screenshots

![Image](https://github.com/gripss-x/GRIPSS-X/assets/152488634/fa7fd96d-2910-4e69-8e78-823b697b17d0)

.

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by Marcel-Hahn** [comment]
Hier ist es auch möglich eigene Zertifizierungen anzulegen 
![image](https://github.com/gripss-x/GRIPSS-X/assets/866882/00aeff52-cd77-4801-bb0a-598f4ba2fc3f)

Hier sollten wir nur mal dringend eine Überprüfung einführen, bevor wir die neuen Zertifikate für jeden frei geben. Ich kann jetzt auch die Zertifizierung von Matthias auswählen. Da steht ja wieder nach einiger Zeit nur Quatsch zur Auswahl.

**Comment by Marcel-Hahn** [comment]
Man kann ja Werte anlegen, daher schließe ich das
