### ISSUE TITLE
Editieren eines Zertifikats nicht möglich

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#49]
*Beschreibe den Bug**
Eine klare Beschreibung des auftretendes Bugs

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
1. Klicke auf Zertifikat editieren

**Erwartetes Verhalten**
Statt des Formulars für das Kreieren eines neuen Zertifikats muss die Maske für das Editieren geöffnet werde

**Screenshots**
Siehe Screenshot

![Image](https://github.com/gripss-x/GRIPSS-X/assets/152488634/8c4b34d3-26b9-42ab-8789-edaaefc6d173)

.

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by Marcel-Hahn** [comment]
geht bei mir auch nicht
