### ISSUE TITLE
BUG: Passwort Rücksetzung geht nicht

### ISSUE THREAD

**Issue by Ralle311** [gripss-x/GRIPSS-X#5]
Wenn ich mein Passwort zurücksetzen möchte bekomme ich keine Email
![PW Rücksetzen](https://github.com/gripss-x/GRIPSS-X/assets/152156790/6c50f070-258a-4e34-9702-6b6dcebcfc96)

**Comment by Marcel-Hahn** [comment]
hängt mit dem Mailversand zusammen #27
