### ISSUE TITLE
Löschen von Zertifikaten funktioniert nicht

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#50]
*Beschreibe den Bug**
Löschen von Zertifikaten funktioniert nicht

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
1. Zertifikat löschen

![Image](https://github.com/gripss-x/GRIPSS-X/assets/152488634/1b6472e0-1ccb-4407-a45b-31d7e6eeffdf)

**Erwartetes Verhalten**
Eine klare Beschreibung darüber, welche Funktion hier erwartet worden ist.

**Screenshots**
Wenn möglich, Screenshots ergänzen.

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by Marcel-Hahn** [comment]
Das löschen wird glaube nur nicht bestätigt und die liste nicht neu geladen. Wenn du selber auf aktualisieren klickst oder sie Seite neu lädst, ist das Zertifikat bei mir gelöscht

**Comment by sadusmatthias** [comment]
@Marcel-Hahn 
Du hast Recht. Die Anzeige sollte aber sofort aufgefrischt werden. Ansonsten ist es verwirrend. 
[issue_50.zip](https://github.com/gripss-x/GRIPSS-X/files/13612372/issue_50.zip)

**Comment by Marcel-Hahn** [comment]
Behoben mit Version v2024.1.0-2611
