### ISSUE TITLE
Warum wird zwischen Anfrage und Ausschreibung unterschieden?

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#52]
**Als ** [Beschreiben: Nutzer aus dem Unternehmen], **möchte ich** Y **sodass** Z.
Anfrage und Ausschreibung unterscheiden sich nur geringfügig in ihrer Bedeutung. Macht es wirklich Sinn, zwischen Anfragen und Ausschreibungen zu unterscheiden:

### Beispiele

![Image](https://github.com/gripss-x/GRIPSS-X/assets/152488634/3fc9aeee-128e-4879-a7cf-b7f50d7a9cc8)

### Akzeptanzkriterien
- [ ] Feld XY
- [ ] Farbe muss blau sein

### Ressourcen:
* weitere Informationen, Screenshots, Beispiele etc.

**Comment by sadusmatthias** [comment]
Ich verstehe die Logik mit der Ausschreibung und Anfrage gar nicht.
Warum muss zuerst verpflichtend eine Ausschreibung erstellt werden, bevor eine Anfrage erstellt wird? 

Ein weiterer Test ergibt wenig Sinn, bis diese grundsätzliche Frage geklärt ist.

**Comment by Marcel-Hahn** [comment]
Die Anfrage ist so gedacht, dass man entweder über eine Anfrage bestimmte unternehmen zur Teilnahme einer Ausschreibung auffordern kann oder über das Unternehmens-Matching (das bei mir gerade nicht richtig geht #17) zu Fertigungsverfahren (die demnächst Leistungen heißen werden #16) 

Was aber absolut Sinn machen würde, ist dass wenn man hier über die Anfragenseite anfragen erstellt,
![image](https://github.com/gripss-x/GRIPSS-X/assets/866882/a1fffe99-30da-4b13-8663-06cce192b3ec)
die gleichen Möglichkeiten bekommt, wie über das Unternehmens-Matching
![image](https://github.com/gripss-x/GRIPSS-X/assets/866882/ca103553-61ed-487f-8551-54193e45d70c)

![image](https://github.com/gripss-x/GRIPSS-X/assets/866882/e96cbd3a-975c-440e-98f8-a509660e6037)

**Comment by sadusmatthias** [comment]
@Marcel-Hahn 
Ich befürchte das wir die Begriffe zuerst spezifizieren müssen. So wie diese im GRIPSS-X-Cloud benutzt werden, sind sie nicht praxistauglich.

Weber Unternehmensgruppe verschickt Hunderte Anfragen an Unterlieferanten pro Jahr. Weber hat aber noch nie eine Ausschreibung verschickt. Wenn also unser Einkäufer im GRIPSS-X-Cloud versucht, eine Anfrage für Materiallieferung zu erstellen und das System von ihm verlangt, zuerst eine Ausschreibung zu generieren, dann klickt er auf Beenden mit dem Kommentar: "Was soll der S....". Und das wird das letzte Mal, dass er sich mit dem Thema GRIPSS-X auseinandergesetzt hat.

Zu Begriffsklärung:
In meiner beruflichen Vergangenheit gab es **entweder** eine Ausschreibung **oder** eine Anfrage. Ich habe noch nie als Bieter eine Anfrage **und** eine Ausschreibung zum gleichen kaufmännischen Vorgang erhalten. Die Ausschreibung ist eine besondere Art der Anfrage, bei der der Leistungsumfang klar definiert ist und die Angebote grundsätzlich nur den Preis enthalten sollen. Typische Anwendungsbereiche für Ausschreibungen sind:

1. Öffentliche Projektmaßnahmen (Es wird nur der Festpreis angefragt)
2. Rahmenverträge durch die Industrie (es wird nur der Faktorpreis angefragt)

Sowohl bei Anfragen als auch bei Ausschreibungen gibt es eine Art Einladung - einen Brief mit der bitte um die Zusendung eines unverbindlichen Angebotes. Dieser Brief wird manchmal als Anfrage bezeichnet. Das ist aber nicht korrekt. Man kann eine Einladung zur Teilnahme an einer Ausschreibung verschicken, dies ist aber keine Anfrage.

Im Englischen Sprachgebrauch gibt es diese Unterscheidung:

Request for proposal (RFP) = Anfrage
Invitation to bid (ITB) = Ausschreibung

Vorschlag für die Umsetzung in GRIPSS-X-Cloud:

Der Bereich Anfragen wir eliminiert.
Der Bereich Ausschreibung wird zu Anfragen umbenannt
Im Menü "Anfragen erstellen" gibt es ein Optionsfeld "Ausschreibung". Wenn dieser aktiviert wird, wird die Anfrage als Ausschreibung bezeichnet. Ansonsten wird die Abfrage als normale Anfrage behandelt.

**Comment by Marcel-Hahn** [comment]
@sneumanniits ich glaub, wir sind da gar nicht so weit auseinander, können da gerne nochmal nächste Woche zu telefonieren.

Was glaube ich auch ganz gut funktionieren könnte ist, wenn wir die Ausschreibungen Projekte nennen.
Dann kann man selber Anfragen zu Dienstleistungen in dem Projekt schicken oder das durch das KI Matching automatisieren.
Bekommt dann Angebote zu den Anfragen, die man dann beauftragen kann. 

Den Bereich Anfragen würde ich aber trotzdem behalten. Dort kann man dann projektbezogen Anfragen erstellen oder frei zu einer beliebigen Dienstleistung

Dann hätte wir die Bereiche: Angebote, Anfrage und Projekte

Was hältst du davon?
