### ISSUE TITLE
User Story - Template

### ISSUE THREAD

**Issue by canazkan** [gripss-x/GRIPSS-X#6]
**Als ** [Beschreiben: Nutzer aus dem Unternehmen], **möchte ich** Y **sodass** Z.
_Beschreibung_

### Beispiele
_Screenshots oder Code_

### Akzeptanzkriterien
- [ ] Feld XY
- [ ] Farbe muss blau sein

### Ressourcen:
* weitere Informationen, Screenshots, Beispiele etc.

**Comment by Marcel-Hahn** [comment]
@canazkan pflegt du das noch als template ein?
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by canazkan** [comment]
@Marcel-Hahn du müsstest mir noch paar mehr Rechte freischalten damit ich die templates einpflegen kann. War so als normaler user anscheinend nicht möglich
