### ISSUE TITLE
Fertigungsschritte

### ISSUE THREAD

**Issue by JillianDosReis** [gripss-x/GRIPSS-X#63]
Die Erstellung von Ausschreiben ist nur bedingt möglich, da die Auswahl von Fertigungsschritten nicht möglich ist und die eingegeben Tätigkeiten nicht an genommen werden. 
Es ist schwer herauszufinden, welche Tätigkeiten angenommen werden können und welche nicht. 

### Beispiele
![image](https://github.com/gripss-x/GRIPSS-X/assets/152158208/a861c194-c64c-4a08-8cf9-f625f891c156)

### Akzeptanzkriterien
- [ ] Feld XY
- [ ] Farbe muss blau sein

### Ressourcen:
* weitere Informationen, Screenshots, Beispiele etc.

**Comment by Marcel-Hahn** [comment]
Behoben mit Version v2024.1.0-2611
