### ISSUE TITLE
Tätigkeitsbeschreibung

### ISSUE THREAD

**Issue by JillianDosReis** [gripss-x/GRIPSS-X#64]
Es ist ein großer Zeitaufwand, alle Tätigekeiten einer Ausschreibung zu benennen. Dies kann im Alltag zu Problemen führen, weil bei Fehlern, bzw. Auslassen von notwendigen Tätigkeiten, diese im Vertrag der Ausschreibung nicht aufgenommen sind. 
Als Idee könnten Tätigkeiten, die mehrere kleine Tätigkeiten vereinen Auswählbar sein, so dass alle notwendigen Angezeigt werden können. 
### Beispiele
![image](https://github.com/gripss-x/GRIPSS-X/assets/152158208/cb17fb22-466f-4c24-b2f3-690c5c831bbe)

### Akzeptanzkriterien
- [ ] Feld XY
- [ ] Farbe muss blau sein

### Ressourcen:
* weitere Informationen, Screenshots, Beispiele etc.

**Comment by Marcel-Hahn** [comment]
Behoben mit Version v2024.1.0-2611
