### ISSUE TITLE
Bug: Unternehmenseinladung funktioniert nicht

### ISSUE THREAD

**Issue by David-Kikl** [gripss-x/GRIPSS-X#65]
Zwei Mitarbeiter wurden über die Plattform eingeladen, der Einladungslink wurde bestätigt, dem Unternehmen wurde man aber nicht hinzugefügt
![image](https://github.com/gripss-x/GRIPSS-X/assets/152616581/e12d1ac4-1057-4772-a6c7-edc7287aadb6)
![image](https://github.com/gripss-x/GRIPSS-X/assets/152616581/29d0c547-adcf-4491-8fd5-b13f2a82245a)

**Comment by Marcel-Hahn** [comment]
kann ich nicht reproduzieren. @David-Kikl bitte nochmal ausprobieren
