### ISSUE TITLE
Unternehmen kann nicht editiert werden

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#68]
*Beschreibe den Bug**
Unternehmen kann nicht editiert werden

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
siehe Video

[issue.zip](https://github.com/gripss-x/GRIPSS-X/files/13685616/issue.zip)

**Erwartetes Verhalten**
Eine klare Beschreibung darüber, welche Funktion hier erwartet worden ist.

**Screenshots**
Wenn möglich, Screenshots ergänzen.

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by sadusmatthias** [comment]
Ebenfalls ist die Taste "Neues Unternehmen hinzufügen ohne Funktion"

**Comment by WEMaurice173** [comment]
+1

**Comment by ngaxavi** [comment]
Das Video lässt sich nicht abspielen

**Comment by Marcel-Hahn** [comment]
Das sieht mir nach dem gleichen Problem wie hier aus: https://github.com/gripss-x/GRIPSS-X/issues/69#issuecomment-1865819587
Du hast deine aktiven Rollen eingeschränkt und dir dadurch das Recht entzogen. entweder alles Aktivieren oder nichts.
Ich schließe das Issue erstmal, falls es nicht daran liegt, bitte wieder öffnen
