### ISSUE TITLE
Bug-Meldung - Template

### ISSUE THREAD

**Issue by canazkan** [gripss-x/GRIPSS-X#7]
*Beschreibe den Bug**
Eine klare Beschreibung des auftretendes Bugs

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
1. Gehe auf  '...'
2. Klicke auf '....'
3. Scroll runter auf '....'
4. See Bug

**Erwartetes Verhalten**
Eine klare Beschreibung darüber, welche Funktion hier erwartet worden ist.

**Screenshots**
Wenn möglich, Screenshots ergänzen.

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by Marcel-Hahn** [comment]
@canazkan pflegt du das noch als template ein?
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
