### ISSUE TITLE
Menülesite mit ANfragen, etc. nicht verfügbar

### ISSUE THREAD

**Issue by sadusmatthias** [gripss-x/GRIPSS-X#70]
*Beschreibe den Bug**
Wahrscheinlich habe ich irgendeinen Schritt vergessen. Ich sehe aber das Menü für den Zugriff auf Anfragen, Dienstleistungen, etc. nicht

**Reproduktion**
siehe Screenshot

![Image](https://github.com/gripss-x/GRIPSS-X/assets/152488634/0a721d2e-257b-49e2-99ba-79a60a41c043)

**Erwartetes Verhalten**
Eine klare Beschreibung darüber, welche Funktion hier erwartet worden ist.

**Screenshots**
Wenn möglich, Screenshots ergänzen.

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by Marcel-Hahn** [comment]
@sadusmatthias kannst du das irgendwie reproduzieren oder war das Zufall?

**Comment by sadusmatthias** [comment]
Ja, es ist immer noch so.

**Comment by ikramjaffali** [comment]
ja bei mir auch so, ich sehe das Menü für den Zugriff auf Ausschreibung nicht !

**Comment by WEMaurice173** [comment]
+1

**Comment by Marcel-Hahn** [comment]
@sadusmatthias wenn ich mit dein Issue #69 ansehe, könnte es sein, dass du deine Rechte eingeschränkt hast.
Unter deinen User Einstellungen, kann man seine Rechte einschränken, indem man nicht alle Rollen aktiviert. Achte bitte darauf, dass bei "Aktive Rollen" nichts ausgewählt ist, dass heißt dann, dass alle aktiv sind.

https://gripssx.hahnpro.com/settings/roles
![image](https://github.com/gripss-x/GRIPSS-X/assets/866882/6d410f21-183b-400c-a37b-e5875beb0b98)

**Comment by Marcel-Hahn** [comment]
Liegt ganz klar an den Rollen, daher schließe ich das Issue. Falls es nicht daran liegt, bitte wieder öffnen.
