### ISSUE TITLE
Neues Unternehmen kann nicht erstellt werden

### ISSUE THREAD

**Issue by muth1210** [gripss-x/GRIPSS-X#71]
*Beschreibe den Bug**
Unter dem Reiter Unternehmen lässt sich kein neues Unternehmen hinzufügen. Außerdem ist die linke Menüleiste leer.

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
1. Gehe auf  Unternehmen // Gehe auf linke Menüleiste
2. Klicke auf Neues Unternehmen hinzufügen 
3. Nichts passiert

**Erwartetes Verhalten**
Maske zum Unternehmen hinzufügen erscheint

**Screenshots**
Wenn möglich, Screenshots ergänzen.

**Desktop (please complete the following information):**
- OS: [Microsoft]
- Browser [chrome]

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by Marcel-Hahn** [comment]
da scheint nur die Berechtigung zu fehlen. Bitte einmal direkt mit dem Usernamen melden, dann schalten wir das frei
