### ISSUE TITLE
Bei Ausschreibungen können Zertifikate/ Qualifikation kann nicht eingefügt werden, obwohl es man Ende angezeigt wird 

### ISSUE THREAD

**Issue by JillianDosReis** [gripss-x/GRIPSS-X#73]

**Comment by Lennnard** [comment]
Ich kann neue Zertifikate hinzufügen.
![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152264718/90a12e4e-f1aa-4b30-8874-2beb2fa46aed)

Sobald ich allerdings auf die Leistungen wechsel und dann zurück auf Allgemein wechsel, werden diese nicht mehr angezeigt
![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152264718/57bafb7d-f725-4337-b908-9a6cc55d0d12)
