### ISSUE TITLE
Beim Speichern meines Angebots wurden die Dokumente nicht, die ich hinterlegt habe nicht mit gespeichert. 

### ISSUE THREAD

**Issue by JillianDosReis** [gripss-x/GRIPSS-X#74]
*Beschreibe den Bug**
Eine klare Beschreibung des auftretendes Bugs

**Reproduktion**
Schritte um diesen Bug hervorzurufen:
1. Gehe auf  '...'
2. Klicke auf '....'
3. Scroll runter auf '....'
4. See Bug

**Erwartetes Verhalten**
Eine klare Beschreibung darüber, welche Funktion hier erwartet worden ist.

**Screenshots**
Wenn möglich, Screenshots ergänzen.

**Desktop (please complete the following information):**

**Zusätzliche Informationen**
Weitere Informationen, die nützlich sein können.

**Comment by Lennnard** [comment]
Beim Speichern der Ausschreibung tritt ein Fehler durch das Hochladen von Dateien auf.
![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152264718/7a3c3614-be73-4fdf-a3a1-cefc95fef65f)
