### ISSUE TITLE
Speichern eine Ausschreibung wird nicht bestätigt

### ISSUE THREAD

**Issue by Lennnard** [gripss-x/GRIPSS-X#77]
Das Speichern einer Ausschreibung wird leider nicht deutlich bestätigt.
Und es steht auch weiterhin "Neue Ausschreibung" über dieser.
Das kann schnell zu Verwirrungen und Mehrfach-Erstellungen führen.
![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152264718/520d8d58-84a5-4c9d-84d8-a3cc798822e0)

**Comment by Rainer-Fink** [comment]
Wird durch Popup bestätigt. Evtl. kein Seitenwechsel - dadurch anders als sonst bei Erstelltungen ?
