### ISSUE TITLE
Ausschreibungen: Es ist möglich Ausschreibungen von anderen Unternehmen zu bearbeiten.

### ISSUE THREAD

**Issue by Lennnard** [gripss-x/GRIPSS-X#78]
Ich kann sowohl Ausschreibungen anderer Unternehmen bearbeiten als auch löschen.

Des weiteren ist es ein bisscehn verwirrend, dass man durch einen Doppelklick auf die eigene Ausschreibung nicht in den Bearbeitungsmodus wechselt.

**Comment by Rainer-Fink** [comment]
- evtl. beim Bearbeiten und Löschen nur keine sinnvolle Fehlermeldung?
   - natürlich sollte die Bearbeitenansicht gar nicht geöffnet werden, wenn man diese nicht bearbeiten darf -> direkt nur in "Ansicht"

**Comment by Rainer-Fink** [comment]
sollte behoben sein
