### ISSUE TITLE
BUG: Neue Mitarbeiter können nicht hinzugefügt werden

### ISSUE THREAD

**Issue by Lennnard** [gripss-x/GRIPSS-X#8]
Nach dem Erstellen des Unternehmens können keine weiteren Mitarbeiter hinzugefügt werden. Ich habe mit verschiedenen Lese- und Adminrechten experimentiert.

![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152264718/541f306f-a888-4e80-aede-f70f36e8139b)

**Comment by Marcel-Hahn** [comment]
#27
