### ISSUE TITLE
Anfragen/Angebote Mitteilungen

### ISSUE THREAD

**Issue by Lennnard** [gripss-x/GRIPSS-X#82]
Ich habe eine Anfrage erstellt.

Nachdem diese angenommen wurde, habe ich die Nachricht erhalten, dass ich eine Anfrage erhalten habe.
![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152264718/89c48af1-4ed6-48ce-81a7-ed9403d6b291)

Wenn ich auf diese Nachricht klicke, kommt ein Fehler.
![grafik](https://github.com/gripss-x/GRIPSS-X/assets/152264718/cbc9dd1c-c8ee-4848-8ed5-8aab79e93e62)
Bei Angeboten tritt der gleiche Fehler auf.

Benachrichtigungen sind nicht an das Unternehmen gebunden, sondern an den Benutzer

**Comment by Rainer-Fink** [comment]
The problem is an invalid / old url. This should be fixed. (Fixes the application not found error)
