### ISSUE TITLE
Bug: Ausschreibungen nicht ersichtlich

### ISSUE THREAD

**Issue by David-Kikl** [gripss-x/GRIPSS-X#96]
Weder die Ausschreibungen, die im gleichen Unternehmen erstellen worden sind (in unserem Beispiel Fraunhofer Test), als auch die Angebote sind nicht einsehbar. Lediglich der Ersteller der Ausschreibungen sieht seine eigenen, als Mitarbeiter der selben Firma sehe ich diese nicht.

**Comment by David-Kikl** [comment]
Links: Daniel = Ersteller, Rechts: David = selbes Unternehmen (bei gleichen Rollen). als Mitarbeiter der gleichen Firma ist für mich weder Anfrage, Angebot und Projekte (Ausschreibungen) einsehbar. 
![image](https://github.com/gripss-x/GRIPSS-X/assets/152616581/a6bb1977-0de5-47ab-b069-3be7da07667b)
![image](https://github.com/gripss-x/GRIPSS-X/assets/152616581/0b88d2d8-f4f8-4cff-95d3-aa416cd4e42e)
![image](https://github.com/gripss-x/GRIPSS-X/assets/152616581/9477ef64-8014-491a-a650-e477c2dcdd32)
![image](https://github.com/gripss-x/GRIPSS-X/assets/152616581/3fc89386-5839-4ffd-8e7a-e8e4f18780cc)
![image](https://github.com/gripss-x/GRIPSS-X/assets/152616581/eb936bcd-5ff4-4621-ad82-f1cd133c89dd)

**Comment by Marcel-Hahn** [comment]
Das ist ein Problem mit den aktiven Rollen. 
Hier muss die public rolle aktiv sein. Wir arbeiten gerade daran, dass man darauf nicht achten muss und die immer aktiv ist
![image](https://github.com/gripss-x/GRIPSS-X/assets/866882/b407e000-de8e-4987-b2a3-6d42a2e97f32)
